[package]
name = "socket-communication"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { version = "1.11.0", features = ["v4", "serde"] }
serde = { version = "1.0.216", features = ["derive"]}
serde_json = {version = "*"}
